dist: trusty
sudo: required

language: R

install: true

script: true

after_success:
    - sudo apt-get install texlive-latex-extra
    - cd docs
    - make travis && cd ..

deploy:
    provider: releases
    api_key: "$GH_TOKEN"
    file: docs/persimmon.pdf
    skip_cleanup: true
    overwrite: true

# Only run CI on master
branches:
    only:
        - master

