dist: trusty
sudo: required

language: R

install: true

script: true

after_success:
    - sudo apt-get install texlive-latex-extra
    - cd docs
    - wget http://mirrors.ctan.org/macros/latex/contrib/standalone.zip
    - unzip standalone.zip
    - cd standalone
    - wget http://texdoc.net/texmf-dist/tex/generic/ydoc/ydocstrip.tex
    - xelatex standalone.ins
    - cd .. && mv standalone/* .
    - make travis && cd ..

deploy:
    provider: releases
    api_key: "$GH_TOKEN"
    file: docs/persimmon.pdf
    skip_cleanup: true
    overwrite: true
    on:
        branch:
            - master

# Only run CI on master
branches:
    only:
        - master
        - dev

