language: R

install: true

script: true

after_success:
    make -C docs

deploy:
    provider: releases
    api_key: "$GH_TOKEN"
    file: docs/persimmon.pdf
    skip_cleanup: true
    overwrite: true

# Only run CI on master
branches:
    only:
        - master

