dist: trusty  # 2014 Ubuntu, whoooo!
sudo: required  # Necesary for installing LaTeX packages

language: python
python: "3.5"

install: true  # No dependencies?

script: true  # No Testing


after_success:  # Build binaries and documentation
    - cd docs  # Time to do documentation
    - sudo apt-get install texlive-latex-extra
    - wget http://mirrors.ctan.org/macros/latex/contrib/standalone.zip && unzip standalone.zip
    - cd standalone
    - wget http://texdoc.net/texmf-dist/tex/generic/ydoc/ydocstrip.tex
    - xelatex standalone.ins
    - cd .. && mv standalone/* .
    - make travis

# Run tests on master & dev
branches:
    only:
        - master
        - dev

# Only deploy on master
deploy:
    provider: releases
    api_key: "$GH_TOKEN"
    file: docs/persimmon.pdf
    skip_cleanup: true
    overwrite: true
    on:
        branch:
            - master

notifications:
    email: false  # Stop bothering me

