
branches:
    only:
        - dev
        - master

environment:
    global:
        MINICONDA: "C:\\Miniconda35-x64"
    matrix:
        - PYTHON: "C:\\Python35-x64"

init:
    - "SET PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PYTHON%;%PYTHON%\\Scripts;%PATH%"

install:
    - conda install --yes numpy scipy pandas scikit-learn pip
    - pip install --requirement requirements.txt
    - pip install kivy.deps.sdl2 kivy.deps.angle #kivy.deps.glew
    - pip install PyInstaller

build: false

after_test:
    - PyInstaller persimmon.spec
    #- 7z a persimmon.7z dist\persimmon_debug

artifacts:
    - path: dist/persimmon.exe

deploy:
    provider: GitHub
    artifact: dist/persimmon.exe
    draft: true
    prerelease: true
    description: test
    auth_token: "%GITHUB_AUTH%"
    on:
        branch:
            - dev
            - master

