
branches:
    only:
        - dev
        - master

environment:
    global:
        MINICONDA: "C:\\Miniconda35-x64"
    matrix:
        - PYTHON: "C:\\Python35-x64"

init:
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"

install:
    - conda install --yes numpy scipy pandas scikit-learn
    - pip install --requirement requirements.txt
    - pip install PyInstaller kivy.deps.sdl2 kivy.deps.angle #kivy.deps.glew

build: false

after_test:
    - python -m PyInstaller persimmon_debug.spec
    - 7z a persimmon.7z dist\persimmon_debug

artifacts:
    - path: persimmon.7z

deploy:
    provider: GitHub
    artifact: persimmon.7z
    draft: true
    prerelease: true
    description: test
    auth_token: "%GITHUB_AUTH%"
    on:
        branch:
            - dev
            - master

