branches:
    only:
        - dev
        - master

environment:
    global:
        MINICONDA: "C:\\Miniconda35-x64"
        PYTHON_PIP: "C:\\Python35-x64\\Scripts\\pip"
    matrix:
        - PYTHON: "C:\\Python35-x64"

init:
    - "SET PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PYTHON%;%PYTHON%\\Scripts;%PATH%"

install:
    - conda install --yes numpy scipy pandas scikit-learn pip
    - pip install --requirement requirements.txt
    - pip install kivy.deps.sdl2 kivy.deps.angle
    - pip install PyInstaller

build: false

before_test:
    - "%PYTHON_PIP% install mypy"
    - "%PYTHON%\\Scripts\\mypy --version"
    - mypy --version
    - "%PYTHON%\\Scripts\\mypy --package persimmon --config-file mypy.ini"

before_deploy:
    - PyInstaller persimmon.spec
    #- 7z a persimmon.7z dist\persimmon_debug

artifacts:
    - path: dist/persimmon.exe

deploy:
    provider: GitHub
    artifact: dist/persimmon.exe
    draft: true
    prerelease: true
    description: Windows Executable
    auth_token: "%GITHUB_AUTH%"
    on:
        branch:
            - master

