
branches:
    only:
        - dev
        - master

environment:
    global:
        MINICONDA: "C:\\Miniconda35-x64"
    matrix:
        - PYTHON: "C:\\Python35-x64"

init:
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"

install:

    #- "conda create -q -n test-environment python=%PYTHON_VERSION%"
    #- conda config --add channels conda-forge
    #- activate test-environment
    - conda install --yes numpy scipy pandas scikit-learn
    - pip install --requirement requirements.txt
    - pip install PyInstaller kivy.deps.sdl2 kivy.deps.glew

build: false

after_test:
    - python -m PyInstaller persimmon_debug.spec

artifacts:
    - path: dist/*

deploy:
    provider: GitHub
    on:
        branch:
            - master

